local library = loadstring(game:HttpGet("https://raw.githubusercontent.com/naypramx/Ui__Project/Script/XeNonUi", true))()
library:CreateWatermark("Center Hub No.1") -- Config แตกนะเดียวค่อยแก้รอเน็ตมาก่อน By MeowX#0001
local CenterHubNo1 = library:CreateWindow("UI EDIT BY NAYPRAMXD :) ",Enum.KeyCode.RightControl)
local Tab = CenterHubNo1:CreateTab("TAB CENTERHUB")
local Sector1 = Tab:CreateSector("SECTOR CENTERHUB","left")
Sector1:AddLabel("LABEL BY CENTERHUB")
Sector1:AddToggle("TOGGLE BY CENTERHUB",false,function(t)
   print(t)
end)
Sector1:AddButton("BUTTON BY CENTERHUB",function()
    print("CENTERHUB")
end)
Sector1:AddDropdown("Multi DropdownText by Centerhub",{"None","IDK","odl2"},"None",true,function(t)
    print(t)
end)
Sector1:AddDropdown("DropdownText by Centerhub",{"None","IDK","odl2"},"None",false,function(t)
    print(t)
end)
local Dropdownxd = Sector1:AddToggle("Toggle With Dropdown",false,function(t)
   print(t)
end)
Dropdownxd:AddDropdown({"None","IDK","odl2"},"None",false,function(t)
    print(t)
end)
local Dropdow2nxd = Sector1:AddToggle("Toggle With Dropdown Multi",false,function(t)
   print(t)
end)
Dropdow2nxd:AddDropdown({"None","IDK","odl2"},"None",true,function(t)
    print(t)
end)
local Sector2 = Tab:CreateSector("SECTOR CENTERHUB 2","Right")
 tablexd = {"xd1","table2","pussy3"}
local dropdoxwn = Sector2:AddDropdown("DropdownText Select Weapon",tablexd,"None",false,function(t)
    print(t)
end)
Sector2:AddButton("Refresh Test",function()
    table.clear(tablexd)
    for i,v in pairs(tablexd) do
    dropdoxwn:Add(v)
    end
end)
local Sector3 = Tab:CreateSector("SECTOR CENTERHUB 3","Right")
Sector3:AddSlider("Slider By Center",20,50,100,1,function(x)
    print(x)
end)
local Sector4 = Tab:CreateSector("SECTOR CENTERHUB 4","left")
Sector4:AddColorpicker('Color picker',Color3.fromRGB(255, 255, 255),function(t)
    print(t)
end)
Sector3:AddSeperator("Seperator By Center")
local Tab2 = CenterHubNo1:CreateTab("Config") -- Config แตกนะเดียวค่อยแก้รอเน็ตมาก่อน By MeowX#0001
Tab2:CreateConfigSystem() -- Config แตกนะเดียวค่อยแก้รอเน็ตมาก่อน By MeowX#0001 -- ห้ามนำไปแจกต่อนะจ๊ะ XD